; GALBA2 configuration file

[paths]
samples_file = samples.csv
augustus_config_path = augustus_config

[containers]
galba_image = docker://katharinahoff/galba-notebook:latest

[SLURM_ARGS]
cpus_per_task = 8
mem_of_node = 16000
max_runtime = 60

[PARAMS]
skip_optimize_augustus = 1
skip_busco = 1
run_omark = 0
use_dev_shm = 0
no_cleanup = 1
disable_diamond_filter = 0
translation_table = 1
